import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  icon: {
    width: 18,
    height: 18,
    marginTop: 4,
  },
  linkBk: {
    color: 'gray',
    textAlign: 'left',
    fontSize: 10,
    fontWeight: '200',
    paddingLeft: 50,
    paddingRight: 50,
    paddingBottom: 30,
  },
  linkBold: {
    textAlign: 'left',
    fontWeight: '700',
    paddingLeft: 40,
    paddingRight: 50,
    paddingBottom: 16,
  },
  linkOrange: {
    color: '#EE414C',
    textAlign: 'left',
    fontSize: 11,
    fontWeight: '200',
    paddingLeft: 50,
    paddingRight: 50,
    paddingBottom: 6,
  },
  topBold: {
    textAlign: 'left',
    fontWeight: '600',
    paddingTop: 2,
    paddingLeft: 10,
    fontSize: 17,
    color: '#000000',
  },
  inputPh: {
    marginLeft: 40,
    marginRight: 10,
    marginBottom: 10,
    height: 40,
    backgroundColor: '#F1F1F1',
    borderRadius: 10,
    paddingHorizontal: 10,
    width: 200,
  },
  input: {
    marginLeft: 40,
    marginRight: 50,
    marginBottom: 10,
    height: 40,
    backgroundColor: '#F1F1F1',
    borderRadius: 10,
    paddingHorizontal: 10,
  },
  container: {
    flex: 1,
    backgroundColor: 'white',
  },
  topBox: {
    height: 100,
    paddingTop: 30,
    paddingBottom: 10,
    paddingLeft: 20,
    justifyContent: 'flex-start',
    alignItems: 'flex-start',
    flexDirection: 'row',
  },
  midBox: {
    height: 560,
    paddingTop: 10,
  },
  btBox: {
    height: 100,
    paddingTop: 10,
  },
  mBtn1: {
    backgroundColor: '#E2E2E2',
    paddingVertical: 10,
    padding: 10,
    alignItems: 'center',
    borderRadius: 10,
    width: 110,
    height: 40,
    lineHeight: 40,
  },
  mBtn2: {
    backgroundColor: '#80D2F4',
    fontWeight: '500',
    paddingVertical: 10,
    padding: 10,
    alignItems: 'center',
    borderRadius: 10,
    width: 110,
    height: 40,
    lineHeight: 40,
  },
  pwBtn1: {
    backgroundColor: '#E2E2E2',
    fontWeight: '500',
    paddingHorizontal: 110,
    paddingVertical: 10,
    marginLeft: 50,
    marginRight: 50,
    alignItems: 'center',
    borderRadius: 10,
    marginBottom: 10,
  },
  pwBtn2: {
    fontWeight: '500',
    paddingHorizontal: 110,
    paddingVertical: 10,
    marginLeft: 50,
    marginRight: 50,
    alignItems: 'center',
    borderRadius: 10,
    marginBottom: 10,
  },
  activeButton: {
    backgroundColor: '#80D2F4',
    fontWeight: '500',
  },
  disabledButton: {
    backgroundColor: '#CCCCCC', // 비활성화되었을 때 배경색
  },
});

export default styles;
